GLOG_logtostderr=1 /home/dangmanhtruong95/C3D-master_JPG/build/tools/finetune_net.bin /home/dangmanhtruong95/Cuong/Cuong_C3D_files/finetuning/c3d_sport1m_finetuning_solver.prototxt /home/dangmanhtruong95/Cuong/Cuong_C3D_files/pretrained_model_and_volume_mean/conv3d_deepnetA_sport1m_iter_1900000

